esphome:
  name: pm2-5-air-quality-kit
  friendly_name: M5Stack PM2.5 Air Quality Kit SHT30

esp32:
  variant: esp32
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "lGHEUmnPS97HYBubPYNM4XkfKPgBbGIFoQ8zUdEiU1s=" # example key, you are supposed to generate a new one

ota:
  - platform: esphome
    password: "0a4314ac943a39b44a906448189202ec"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Pm2-5-Air-Quality-Kit"
    password: "iLPwdoM9twIJ"

captive_portal:

packages:
  - !include ../../commom/pm2_5-air-quality-kit-base.yaml