esphome:
  name: unit-tube-pressure
  friendly_name: M5Stack Unit Tube Pressure

esp32:
  variant: esp32s3
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "8ratEFYK2ucP2NGR20RlHE02N41L3b92IX+/vqqvcUU=" # example key, you are supposed to generate a new one

ota:
  - platform: esphome
    password: "fb969e9338634640cf1c48ec89f1c78f" # example passwd, you are supposed to generate a new one

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "Tubepressure Fallback Hotspot"
    password: "bKYWUw1jrJQV"

captive_portal:
    
sensor:
  - platform: adc
    pin: GPIO1
    id: adc_voltage
    attenuation: 11db
    update_interval: 100ms
    unit_of_measurement: "V"
    accuracy_decimals: 3
    filters:
      - multiply: 3.3

  - platform: template
    name: "Pressure"
    unit_of_measurement: "kPa"
    accuracy_decimals: 2
    update_interval: 100ms
    lambda: |-
      float K = 100.0;
      float B = 110.0;
      float voltage = id(adc_voltage).state;  // 单位 V
      float P = voltage * K - B;
      return P;
