esphome:
  name: unit-cams3-5mp
  friendly_name: M5Stack Unit CamS3 5MP

esp32:
  variant: esp32s3
  framework:
    type: esp-idf

psram:
  mode: octal
  speed: 80MHz 
  
# Enable logging
logger:
  level: DEBUG   

# Enable Home Assistant API
api:
  encryption:
    key: "mLTyVD5L13T7hvkdRr9ardNbXYYWmBOo6l7kjg5OSdI=" # example key, you are supposed to generate a new one

ota:
  - platform: esphome
    password: "6aacaa1492f5e0eab0b7ce5af43087bc" # example passwd, you are supposed to generate a new one

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Camer Fallback Hotspot"
    password: "nSPRG7FiYdct"

captive_portal:

switch:
  - platform: gpio
    name: "Active LED"
    pin:
      number: GPIO14
      inverted: true
    restore_mode: ALWAYS_ON

i2c:
  - id: camera_i2c
    sda: GPIO17
    scl: GPIO41
    scan: true

esp32_camera:
  name: "PY260 camera"
  external_clock:
    pin: GPIO11
    frequency: 20MHz
  i2c_id: camera_i2c
  data_pins: [GPIO6, GPIO15, GPIO16, GPIO7, GPIO5, GPIO10, GPIO4, GPIO13]
  vsync_pin: GPIO42
  href_pin: GPIO18
  pixel_clock_pin: GPIO12
  reset_pin: GPIO21
  resolution: 320X240
  jpeg_quality: 12
