# ----------------------------------------------------------------
# M5Stack ESP32-P4 (tab5) Home Assistant HMI Configuration
# 統合版: 天気表示 + レイアウト最適化 (日付を見出し下へ移動)
# ----------------------------------------------------------------

font:
  - file: "https://raw.githubusercontent.com/Templarian/MaterialDesign-Webfont/master/fonts/materialdesignicons-webfont.ttf"
    id: extra_icon
    size: 48
    bpp: 4
    glyphs: [
      "\U000F050F", "\U000F058E", "\U000F0F30", "\U000F056E", "\U000F0A1D",
      "\U000F0335", "\U000F0336", "\U000F0F54", "\U000F0F55", "\U000F001B",
      "\U000F0493", "\U000F08BB", "\U000F0142", "\U000F1805", "\U000F1804",
      "\U000F18DE", "\U000F18DD", "\U000F0425", "\U000F07E4", "\U000F1B5A",
      "\U000F05A9", "\U000F109B", "\U000F0156", "\U000F0415", "\U000F0374",
      "\U000F00DF", "\U000F03D8"
    ]

  - file: "https://raw.githubusercontent.com/Templarian/MaterialDesign-Webfont/master/fonts/materialdesignicons-webfont.ttf"
    id: extra_icon_64
    size: 64
    bpp: 4
    glyphs: [
      "\U000F0D80", # mdi:home-floor-1
      "\U000F0599", # mdi:weather-sunny
      "\U000F0590", # mdi:weather-cloudy
      "\U000F0595", # mdi:weather-partly-cloudy
      "\U000F0596", # mdi:weather-pouring
      "\U000F0703", # mdi:weather-snowy
      "\U000F024B"  # mdi:weather-fog
    ]
  
  - file: gfonts://Montserrat@600
    id: montserrat_24
    size: 24
    bpp: 4

  - file: gfonts://Montserrat@600
    id: montserrat_32
    size: 32
    bpp: 4

  - file: gfonts://Montserrat@600
    id: montserrat_48
    size: 48
    bpp: 4

  - file: gfonts://Montserrat@600
    id: montserrat_96
    size: 96
    bpp: 4

# Home Assistant 連携 (天気)
text_sensor:
  - platform: homeassistant
    id: weather_condition
    entity_id: weather.forecast_zi_zhai
    on_value:
      then:
        - lambda: |-
            if (x == "sunny" || x == "clear-night") id(weather_icon_label).set_text("\U000F0599");
            else if (x == "cloudy") id(weather_icon_label).set_text("\U000F0590");
            else if (x == "partlycloudy") id(weather_icon_label).set_text("\U000F0595");
            else if (x == "rainy" || x == "pouring") id(weather_icon_label).set_text("\U000F0596");
            else if (x == "snowy") id(weather_icon_label).set_text("\U000F0703");
            else if (x == "fog") id(weather_icon_label).set_text("\U000F024B");
            else id(weather_icon_label).set_text("\U000F0F30");

sensor:
  - platform: homeassistant
    id: exterior_temp
    entity_id: weather.forecast_zi_zhai
    attribute: temperature
    on_value:
      then:
        - lvgl.label.update:
            id: weather_temp_label
            text: !lambda return str_sprintf("%.1f°C", x);

lvgl:
  # --- Style definitions (元の設定を維持) ---
  style_definitions:
    - id: sidebar
      bg_color: 0xE9EFEE
      bg_opa: COVER
      border_opa: TRANSP
      pad_top: 30
      pad_left: 0
      pad_right: 0
      radius: 0
      width: 192
      height: 100%
    - id: nav_btn_container
      bg_opa: TRANSP
      border_opa: TRANSP
      width: 180
      height: 150
    - id: nav_btn_inactivate
      bg_opa: TRANSP
      align: CENTER
      width: 112
      height: 64
      radius: 48
      border_opa: TRANSP
      shadow_opa: TRANSP
    - id: nav_icon_inactivate
      align: CENTER
      text_font: extra_icon
      text_color: 0x3F4948
    - id: nav_label_inactivate
      align: BOTTOM_MID
      text_color: 0x3F4948
      text_font: montserrat_24
    - id: content_container
      align: CENTER
      bg_opa: COVER
      border_opa: TRANSP
      height: 100%
      width: 1080
      x: 96
      pad_top: 120
      pad_left: 30

  # --- Top Layer (Sidebar) ---
  top_layer:
    widgets:
      - obj:
          align: TOP_LEFT
          styles: sidebar
          id: sidebars
          layout:
            type: flex
            flex_flow: COLUMN
            pad_row: 12
            flex_align_main: start
            flex_align_cross: center
          widgets:
            - obj: # Dashboard Button
                styles: nav_btn_container
                widgets:
                  - button:
                      align: center
                      styles: nav_btn_inactivate
                      id: dash_panel_btn
                      checkable: true
                      checked:
                        bg_color: 0xCCE8E7
                      widgets:
                        - label:
                            id: dash_btn_icon
                            styles: nav_icon_inactivate
                            text: "\U000F056E"
                      on_press:
                        - lvgl.page.show: dashboard_page
                  - label:
                      styles: nav_label_inactivate
                      text: "Dashboard"

  # --- Pages ---
  pages:
    - id: dashboard_page
      widgets:
        - obj:
            styles: content_container
            widgets:
              # 左上のタイトルと日付
              - label:
                  text: "Dashboard"
                  text_font: montserrat_48
                  text_color: 0x4A6363
                  x: 30
                  y: 40
              - label:
                  id: date_label
                  text_font: montserrat_24
                  text: "1970-01-01 Thu"
                  text_color: 0x3F4948
                  x: 32
                  y: 95
              
              # 中央の大きな時計
              - label:
                  id: time_label
                  text_font: montserrat_96
                  text: "00:00:00"
                  align: CENTER
                  y: -120 

              # 天気ウィジェット
              - obj:
                  align: CENTER
                  y: 15
                  width: 500
                  height: 120
                  bg_opa: TRANSP
                  border_opa: TRANSP
                  layout:
                    type: FLEX
                    flex_align_main: CENTER
                    flex_align_cross: CENTER
                    pad_column: 25
                  widgets:
                    - label:
                        id: weather_icon_label
                        text_font: extra_icon_64
                        text: "\U000F0F30"
                        text_color: 0x4A6363
                    - label:
                        id: weather_temp_label
                        text_font: montserrat_48
                        text: "--°C"
                        text_color: 0x3F4948

              # 下部の室内センサー
              - obj:
                  width: 850
                  height: 200
                  bg_opa: TRANSP
                  border_opa: TRANSP
                  align: BOTTOM_MID
                  y: -20
                  layout:
                    type: GRID
                    grid_columns: [FR(20), FR(30), FR(20), FR(30)]
                    grid_rows: [FR(1), FR(1)]
                    pad_row: 24
                    pad_column: 24
                  widgets:
                    - label: {text_font: extra_icon, text: "\U000F050F", grid_cell_column_pos: 0, grid_cell_row_pos: 0}
                    - label: {id: temp_label, text_font: montserrat_32, text: "-", grid_cell_column_pos: 1, grid_cell_row_pos: 0}
                    - label: {text_font: extra_icon, text: "\U000F058E", grid_cell_column_pos: 2, grid_cell_row_pos: 0}
                    - label: {id: humi_label, text_font: montserrat_32, text: "-", grid_cell_column_pos: 3, grid_cell_row_pos: 0}
                    - label: {text_font: extra_icon, text: "\U000F07E4", grid_cell_column_pos: 0, grid_cell_row_pos: 1}
                    - label: {id: co2_label, text_font: montserrat_32, text: "- ppm", grid_cell_column_pos: 1, grid_cell_row_pos: 1}
                    - label: {text_font: extra_icon, text: "\U000F1B5A", grid_cell_column_pos: 2, grid_cell_row_pos: 1}
                    - label: {id: iaq_label, text_font: montserrat_32, text: "-", grid_cell_column_pos: 3, grid_cell_row_pos: 1}
