esphome:
  name: switchc6
  friendly_name: M5Stack SwitchC6

esp32:
  variant: esp32
  framework:
    type: esp-idf

logger:
  level: VERBOSE

api:
  encryption:
    key: "X7+AfftIYMa/cDqk1pZ9dug7cas7U3/tg5zghRQ1Gow=" # example key, you are supposed to generate a new one

ota:
  - platform: esphome
    password: "1d25a8a9ad6d2069fd467f15c7795700" # example passwd, you are supposed to generate a new one

external_components:
  - source: github://m5stack/esphome-yaml/components
    components: espnow_switch
    refresh: 0s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Switch Fallback Hotspot"
    password: "TVP1qcPH6I64"

captive_portal:


espnow:
  id: espnow1
  auto_add_peer: true
  peers:
    - XX:XX:XX:XX:XX:XX
  on_broadcast:
    - lambda: |-
        id(sw1).handle_broadcast(data, size);

switch:
  - platform: espnow_switch
    id: sw1
    name: "SwitchC6 Device 1"
    espnow_id: espnow1
    mac_address: "XX:XX:XX:XX:XX:XX"
    retry_count: 40
    retry_interval: 300
